const SYNONYM_MAP = {
  js: "javascript",
  ts: "typescript",
  reactjs: "react",
  "react.js": "react",
  nodejs: "node",
  "node.js": "node",
  expressjs: "express",
  "express.js": "express",
  py: "python",
  golang: "go",
  postgres: "postgresql",
  mongo: "mongodb",
  aws: "amazoncloud",
  amazonwebservices: "amazoncloud",
  gcp: "googlecloud",
  googlecloudplatform: "googlecloud",
  azure: "microsoftcloud",
  k8s: "kubernetes",
  docker: "containerization",
  containers: "containerization",
  led: "leadership",
  lead: "leadership",
  leading: "leadership",
  managed: "management",
  managing: "management",
  manager: "management",
  mentored: "mentorship",
  mentoring: "mentorship",
  swe: "softwareengineer",
  sde: "softwareengineer",
  "software developer": "softwareengineer",
  "software engineer": "softwareengineer",
  btech: "bachelors",
  "b.tech": "bachelors",
  mtech: "masters",
  "m.tech": "masters",
  api: "applicationprogramminginterface",
  apis: "applicationprogramminginterface",
  restapi: "applicationprogramminginterface",
  rest: "applicationprogramminginterface",
  microservice: "microservices",
  ml: "machinelearning",
  ai: "artificialintelligence",
  nlp: "naturallanguageprocessing",
};
function normalizeSynonym(token) {
  const lower = token.toLowerCase();
  return SYNONYM_MAP[lower] || lower;
}
module.exports = { SYNONYM_MAP, normalizeSynonym };
