import jsPDF from "jspdf";
export function downloadAnalysisReport(result, meta = {}) {
  const { jobTitle = "Untitled Role", fileName = "resume", createdAt } = meta;
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = 60;

  const colors = {
    accent: [99, 102, 241],
    good: [22, 163, 74],
    warn: [217, 119, 6],
    bad: [220, 38, 38],
    text: [30, 41, 59],
    muted: [100, 116, 139],
  };

  const scoreColor = (score) => {
    if (score >= 75) return colors.good;
    if (score >= 50) return colors.warn;
    return colors.bad;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...colors.accent);
  doc.text("ATSlay — Resume Analysis Report", margin, y);
  y += 22;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...colors.muted);
  const dateStr = createdAt ? new Date(createdAt).toLocaleString() : new Date().toLocaleString();
  doc.text(`${jobTitle} · ${fileName} · Generated ${dateStr}`, margin, y);
  y += 30;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...colors.text);
  doc.text("Overall ATS Score", margin, y);

  doc.setFontSize(28);
  doc.setTextColor(...scoreColor(result.atsScore));
  doc.text(`${result.atsScore}/100`, pageWidth - margin, y, { align: "right" });
  y += 30;

  const breakdown = [
    ["Keyword Match", result.keywordScore],
    ["Semantic Relevance", result.semanticScore],
    ["Section Coverage", result.sectionScore],
    ["Format Quality", result.formatScore],
  ];

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  breakdown.forEach(([label, value]) => {
    doc.setTextColor(...colors.text);
    doc.text(label, margin, y);
    doc.setTextColor(...scoreColor(value));
    doc.text(`${value}%`, pageWidth - margin, y, { align: "right" });
    y += 18;
  });
  y += 12;

  const drawListSection = (title, items, color, emptyText) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...colors.text);
    doc.text(title, margin, y);
    y += 18;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    if (!items || items.length === 0) {
      doc.setTextColor(...colors.muted);
      doc.text(emptyText, margin, y);
      y += 16;
      return;
    }
    doc.setTextColor(...color);
    const wrapped = doc.splitTextToSize(items.join("  •  "), pageWidth - margin * 2);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 14 + 10;
  };

  drawListSection("Matched Keywords", result.matchedKeywords, colors.good, "No keyword matches found.");
  drawListSection("Missing Keywords", result.missingKeywords, colors.bad, "No major gaps found.");

  if (result.detectedSections || result.missingSections) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...colors.text);
    doc.text("Sections", margin, y);
    y += 18;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...colors.good);
    const detected = (result.detectedSections || []).join(", ") || "None detected";
    doc.text(doc.splitTextToSize(`Detected: ${detected}`, pageWidth - margin * 2), margin, y);
    y += 16;

    doc.setTextColor(...colors.bad);
    const missingS = (result.missingSections || []).join(", ") || "None missing";
    doc.text(doc.splitTextToSize(`Missing: ${missingS}`, pageWidth - margin * 2), margin, y);
    y += 20;
  }

  if (result.suggestions && result.suggestions.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...colors.text);
    doc.text("Suggestions", margin, y);
    y += 18;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...colors.text);
    result.suggestions.forEach((s) => {
      const wrapped = doc.splitTextToSize(`•  ${s}`, pageWidth - margin * 2);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 14 + 4;
    });
  }

  doc.setFontSize(8);
  doc.setTextColor(...colors.muted);
  doc.text(
    "Generated by ATSlay — https://at-slay.vercel.app",
    margin,
    doc.internal.pageSize.getHeight() - 30
  );

  const safeName = jobTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`atslay-report-${safeName}.pdf`);
}
